#If this is set to True, Lord mobs will only spawn from player-killed entities.
player_kill_only: True

#If this is set to True, Lord mobs will spawn from killed mobs summoned by a spawner.
spawner: False

#Do not set this value very high as it will cause lag!
#If you have mythic mobs with large hit-boxes (e.g. Iron Golem) increase the value to 3.
empty_space_spawn: 1

#A Lord Mob will spawn over 'min',  and less than 'max' blocks away from the killed entity.
radius:
  min: 5
  max: 15

#This section maps a minecraft entity to your custom MythicMob Lords.
mobs:
  skeleton:
    #Give a weight for no mob to spawn (otherwise a lord from above will always be summoned)
    no_spawn: 84
    #Specify a list of mythic mobs to spawn and give them a spawn weight
    lords:
      - SkeletalMinion, WITHER_SKELETON  :10
      - SkeletalKnight, SkeletonKing  :1
  zombie:
    no_spawn: 3
    lords:
      - StaticallyChargedSheep :5
      - GIANT :1
  spider:
    lord:
      - CAVE_SPIDER :50
      - AngrySludge :10