radius:
  min: 5
  max: 15


level_range:
  common:
    min: 1
    max: 2
  rare:
    min: 3
    max: 5
  legendary:
    min: 6
    max: 10


probabilities:
  common: 10
  rare: 5
  legendary: 1


mobs:
  skeleton:
    common: [SkeletalMinion, WITHER_SKELETON ]
    rare: [ SkeletalKnight ]
    legendary: [ SkeletonKing ]
  zombie:
    common:
    rare: [ StaticallyChargedSheep ]
    legendary: [ GIANT ]
  spider:
    common: [ CAVE_SPIDER ]
    rare:
    legendary: [ AngrySludge ]