name: BossMobsWithMythicMobs
version: '${project.version}'
main: com.unipi.alexandris.bossmobs.bossmobswithmythicmobs.BossMobsWithMythicMobs
api-version: 1.18
depend: [ MythicMobs ]
authors: [ Antitonius ]
description: My Boss Mobs implementation using Mythic Mobs
website: https://anthonyal.github.io
commands:
  bossmobs:
    description: Command group for BossMobsWithMythicMobs.
    aliases: bm
    permission: bossmobs
permissions:
  bossmobs:
    description: Access to all BossMobsWithMythicMobs commands.
    default: op
